# Generated by Django 5.1.3 on 2025-03-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donorprofile_delete_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='is_donor',
            field=models.BooleanField(default=True),
        ),
    ]
