# Generated by Django 5.1.3 on 2025-03-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donorprofile_is_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='is_donor',
        ),
    ]
