# Generated by Django 5.1.3 on 2025-03-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_remove_donorprofile_is_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='donation_count',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='contact_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='house_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='share_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='blood_group',
            field=models.CharField(default='O+', max_length=3),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
