# Generated by Django 5.1.3 on 2025-03-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_remove_donorprofile_donation_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('alternate_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('share_contact', models.BooleanField(default=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('thalassemia_status', models.BooleanField(default=False)),
                ('house_number', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('willing_to_donate', models.BooleanField(default=True)),
                ('preferred_location', models.CharField(blank=True, choices=[('Hospital', 'Hospital'), ('Blood Bank', 'Blood Bank'), ('Home Pickup', 'Home Pickup')], max_length=20, null=True)),
                ('preferred_time', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=10, null=True)),
                ('can_donate_for_thalassemia', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='donor_profiles/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='donor_ids/')),
                ('health_conditions', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DonorProfile',
        ),
    ]
