# Generated by Django 5.1.3 on 2025-03-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_alter_donor_options_alter_donor_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donation_count',
            field=models.IntegerField(default=0),
        ),
    ]
