# Generated by Django 5.1.3 on 2025-03-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0008_donor_donation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donation_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
