# Generated by Django 5.1.3 on 2025-03-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0010_rename_street_name_donor_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
