# Generated by Django 5.1.7 on 2025-04-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0011_alter_donor_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='can_donate_for_thalassemia',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='health_conditions',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='preferred_location',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='preferred_time',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='willing_to_donate',
        ),
    ]
