# Generated by Django 5.1.3 on 2025-04-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0012_remove_donor_can_donate_for_thalassemia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='donor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='donor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='username',
        ),
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
