# Generated by Django 5.1.3 on 2025-04-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0013_alter_donor_options_alter_donor_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='city',
            field=models.CharField(blank=True, default='Indore', max_length=100, null=True),
        ),
    ]
