# Generated by Django 5.1.7 on 2025-04-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbanks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
