# Generated by Django 5.1.7 on 2025-04-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbanks', '0002_alter_bloodbank_email_alter_bloodbank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
