# Generated by Django 5.1.3 on 2025-04-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_recipientprofile_delete_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('alternate_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('reason_for_request', models.TextField()),
                ('emergency', models.BooleanField(default=False)),
                ('hospital_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('blood_group_needed', models.CharField(max_length=3)),
                ('units_required', models.PositiveIntegerField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='recipient_profiles/')),
            ],
        ),
        migrations.DeleteModel(
            name='RecipientProfile',
        ),
    ]
