# Generated by Django 5.1.3 on 2025-04-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0003_recipient_delete_recipientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='blood_group_needed',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='emergency',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='reason_for_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='units_required',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
