# Generated by Django 5.1.3 on 2025-04-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0004_alter_recipient_blood_group_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
    ]
