# Generated by Django 5.1.3 on 2025-04-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0005_recipient_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='request_status',
        ),
    ]
