# Generated by Django 5.1.3 on 2025-04-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0006_remove_recipient_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
