# Generated by Django 5.1.3 on 2025-05-06 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0007_recipient_latitude_recipient_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='alternate_contact',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='emergency',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='units_required',
        ),
        migrations.AddField(
            model_name='recipient',
            name='blood_units_required',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='urgency',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Critical', 'Critical')], default='Normal', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipient',
            name='blood_group_needed',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='full_name',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
