# Generated by Django 5.1.3 on 2025-05-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0008_remove_recipient_alternate_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
